### ISSUE TITLE
[Feature] 오리알 아이템 구현 (~6/28)

### ISSUE THREAD

**Issue by nninyeong** [KIA-PROGRAMMING-38/Team_Immortal-Sprouts_Pummel-Party#84]
# 설명
- 아이템 - 오리알을 구현합니다.

# 참고자료
https://docs.google.com/document/d/1-N_dwYnBZ-ujvUDqSp37tMPMxlIveSGz7jprIyi8OC8/edit

**Comment by rickythediver** [comment]
오리알 아이템 삭제
